apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-devops-app
  labels:
    app: sample-devops-app
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: sample-devops-app
  template:
    metadata:
      labels:
        app: sample-devops-app
    spec:
      containers:
        - name: sample-devops-app
          image: 3.128.79.118:5000/sampledevops:latest  # Your private registry image
          ports:
            - containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: "production"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: sample-devops-service
spec:
  selector:
    app: sample-devops-app
  ports:
    - protocol: TCP
      port: 80  # Exposed Port
      targetPort: 8080  # Container Port
  type: LoadBalancer  # AWS will assign an external IP
